import Navbar from "@/component/navbar";
import "./globals.css";
import Header from "@/component/header";

export const metadata = {
    title: "Home-Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased h-screen relative`}>
                <Header />
                <div className="transform delay-100">
                        {children}
                </div>
                <Navbar />
            </body>
        </html>
    );
}
