import Navbar from "@/component/navbar";
import "./globals.css";
import Header from "@/component/header";
import SensorProvider from "@/context/sensorProvider";
import ScheduleProvider from "@/context/scheduleProvider";

export const metadata = {
    title: "Home-Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased h-screen relative`}>
                <Header />
                <div className="w-screen relative lg:flex lg:flex-row-reverse">
                    <div className="transform delay-100 flex justify-center lg:flex-grow">
                        <ScheduleProvider>
                            <SensorProvider>
                                {children}
                            </SensorProvider>
                        </ScheduleProvider>
                    </div>
                </div>
                <Navbar />
            </body>
        </html>
    );
}
